name: flutter_wordpress
description: This library uses WordPress REST-API-V2 to provide a way for your application to
  interact with your WordPress website.
version: 0.4.0

homepage: https://github.com/duyhuynh258/flutter_wordpress

environment:
  sdk: '>=3.1.5'

dependencies:
  http: ^1.1.2
